language: python

matrix:
  include:
    - os: linux
      python: "3.6"
    - os: linux
      python: "2.7"
    - os: osx
      language: generic
      install: sudo -H pip install -r requirements.txt

install:
  - pip install -r requirements.txt
script:
  - pytest --cov=./ --doctest-modules

after_success:
  - codecov
