image:
  - Visual Studio 2017

environment:
  matrix:
    - PYTHON_PATH: C:\Python27-x64
    - PYTHON_PATH: C:\Python36-x64

build: off

install:
  - set PATH=%PYTHON_PATH%;%PYTHON_PATH%\Scripts;%PATH%
  - pip install -r requirements.txt

test_script:
  - doit test