coverage:
  precision: 2
  round: down
  range: "90...100"

  status:
    project: no
    patch:
      default:
        threshold: 1.0%
    changes: no

comment:
  layout: "header, diff, changes, tree"
  behavior: default