coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        enabled: yes
        target: 90%
        threshold: 5%
    patch:
      default:
        enabled: no
    changes: no

comment:
  layout: "header, diff, changes, tree"
  behavior: default